### ISSUE TITLE
getpapers issues related to Ocimum articles download from EPMC.

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#41]
ambarish123@ubuntu:~$ getpapers -q "((Ocimum sanctum) OR (Ocimum) OR (Ocimum tenuiflorum) OR (thulasi) OR (tulasi) OR (tulsi) OR (holy basil))" -x -p -a -o Ocimumproject17feb
info: Searching using eupmc API
info: Found 4895 results
warn: This version of getpapers wasn't built with this version of the EuPMC api in mind
warn: getpapers EuPMCVersion: 5.3.2 vs. 6.0.3 reported by api
Retrieving results [==============================] 100% (eta 0.0s)
info: Done collecting results
info: Duplicate records found: 4843 unique results identified
info: Saving result metadata
info: Full EUPMC result metadata written to eupmc_results.json
Potentially unhandled rejection [1] Error: EACCES: permission denied, mkdir '/s0074-02762005000100011'
    at Object.fs.mkdirSync (fs.js:895:18)
    at Function.sync (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/node_modules/mkdirp/index.js:71:13)
    at EuPmc.writeRecord (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:588:10)
    at /home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:226:11
    at Array.forEach (native)
    at EuPmc.handleSearchResults (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:225:20)
    at EuPmc.completeCallback (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:167:11)
    at /home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:97:7
    at Parser.<anonymous> (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/node_modules/xml2js/lib/parser.js:303:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)

#### Please go through the error

**Comment by petermr** [comment]
**Please format this.**
```
ambarish123@ubuntu:~$ getpapers -q "((Ocimum sanctum) OR (Ocimum) OR (Ocimum tenuiflorum) OR (thulasi) OR (tulasi) OR (tulsi) OR (holy basil))" -x -p -a -o Ocimumproject17feb
info: Searching using eupmc API
info: Found 4895 results
warn: This version of getpapers wasn't built with this version of the EuPMC api in mind
warn: getpapers EuPMCVersion: 5.3.2 vs. 6.0.3 reported by api
Retrieving results [==============================] 100% (eta 0.0s)
info: Done collecting results
info: Duplicate records found: 4843 unique results identified
info: Saving result metadata
info: Full EUPMC result metadata written to eupmc_results.json
Potentially unhandled rejection [1] Error: EACCES: permission denied, mkdir '/s0074-02762005000100011'
at Object.fs.mkdirSync (fs.js:895:18)
at Function.sync (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/node_modules/mkdirp/index.js:71:13)
at EuPmc.writeRecord (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:588:10)
at /home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:226:11
at Array.forEach (native)
at EuPmc.handleSearchResults (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:225:20)
at EuPmc.completeCallback (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:167:11)
at /home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:97:7
at Parser. (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/node_modules/xml2js/lib/parser.js:303:18)
at emitOne (events.js:96:13)
at Parser.emit (events.js:191:7)
```

**Comment by petermr** [comment]
I can reproduce the problem:
```
getpapers -q "((Ocimum sanctum) OR (Ocimum) OR (Ocimum tenuiflorum) OR (thulasi) OR (tulasi) OR (tulsi) OR (holy basil))" -x -p -a -o Ocimumproject17feb
info: Searching using eupmc API
info: Found 4895 results
warn: This version of getpapers wasn't built with this version of the EuPMC api in mind
warn: getpapers EuPMCVersion: 5.3.2 vs. 6.0.3 reported by api
Retrieving results [==============================] 100% (eta 0.0s)
info: Done collecting results
info: Duplicate records found: 4843 unique results identified
info: Saving result metadata
info: Full EUPMC result metadata written to eupmc_results.json
Potentially unhandled rejection [1] Error: EACCES: permission denied, mkdir '/s0074-02762005000100011'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:916:18)
    at Function.sync (/usr/local/n/versions/node/6.2.1/lib/node_modules/getpapers/node_modules/mkdirp/index.js:71:13)
    at EuPmc.writeRecord (/usr/local/n/versions/node/6.2.1/lib/node_modules/getpapers/lib/eupmc.js:588:10)
    at /usr/local/n/versions/node/6.2.1/lib/node_modules/getpapers/lib/eupmc.js:226:11
    at Array.forEach (native)
    at EuPmc.handleSearchResults (/usr/local/n/versions/node/6.2.1/lib/node_modules/getpapers/lib/eupmc.js:225:20)
    at EuPmc.completeCallback (/usr/local/n/versions/node/6.2.1/lib/node_modules/getpapers/lib/eupmc.js:167:11)
    at /usr/local/n/versions/node/6.2.1/lib/node_modules/getpapers/lib/eupmc.js:97:7
    at Parser.<anonymous> (/usr/local/n/versions/node/6.2.1/lib/node_modules/getpapers/node_modules/xml2js/lib/parser.js:303:18)
MacBook-Pro-3:tigr2ess pm286$ 
```
This confirms it is not local to you (e.g. it is not disk full or similar).
The key lines are:
```
Potentially unhandled rejection [1] Error: EACCES: permission denied, mkdir '/s0074-02762005000100011'
at Object.fs.mkdirSync (fs.js:895:18)
at Function.sync (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/node_modules/mkdirp/index.js:71:13)
at EuPmc.writeRecord (/home/ambarish123/.nvm/versions/node/v7.10.1/lib/node_modules/getpapers/lib/eupmc.js:588:10)
...
```

My guess is that:
 * it is trying to make a directory and failing. 
 * probably because there is a directory of the same name (see earlier warning).
 
I think this is a rare error, and one for EPMC.  The remedy would be to trap it and continue.
Unfortunately I don't know enough Node to fix it.
I suspect it will occur with low frequency. It will generally not happen in the morning classes
The remedy is probably not to run queries which return such large numbers of hits (e.g. we can do this by slicing by dates.)

**Comment by petermr** [comment]
Amit - can you see if we can use a later version of `getpapers`.

**Comment by petermr** [comment]
This bug occurs when non-PMC articles are used `-a` flag. Please don't use this. There is no fulltext for most of them.
