### ISSUE TITLE
"Test run of new release of ami-jars - ami20190218a" 

### ISSUE THREAD

**Issue by ambarishK** [petermr/tigr2ess#49]
### Test run status of ami-search-cooccur tool/plugin of ami20190218a.jar

```
ambarish123@ubuntu:~$ ami-search-cooccur RiceOROryzanew/ country gene drugs plantparts monoterpene species
0    [main] DEBUG org.contentmine.ami.AMIProcessor  - project name: RiceOROryzanew/ /home/ambarish123
1226 [main] DEBUG org.contentmine.ami.plugins.CommandProcessor  - running NORMA -i fulltext.xml -o scholarly.html --transform nlm2html --project /home/ambarish123/RiceOROryzanew
PMC5991738 .PMC6086036 PMC6173730 PMC6203701 PMC6205584 PMC6208651 PMC6213974 PMC6222575 PMC6249995 PMC6265930 PMC6267922 .PMC6278296 PMC6283022 PMC6311050 PMC6321642 PMC6337394 PMC6339128 PMC6339371 PMC6345233 PMC6357162 running: word; word([frequencies])[{xpath:@count>20}, {w.stopwords:pmcstop.txt stopwords.txt}]
..filter: word([frequencies])[{xpath:@count>20}, {w.stopwords:pmcstop.txt stopwords.txt}]
..summary: word([frequencies])[{xpath:@count>20}, {w.stopwords:pmcstop.txt stopwords.txt}]
..running: search; search([country])[]
..filter: search([country])[]
..summary: search([country])[]
..running: gene; gene([human])[]
91079 [main] DEBUG org.contentmine.ami.dictionary.gene.HGNCDictionary  - is /org/contentmine/ami/plugins/gene/hgnc/hgnc.xml
..filter: gene([human])[]
..summary: gene([human])[]
..running: search; search([drugs])[]
..filter: search([drugs])[]
..summary: search([drugs])[]
..running: search; search([plantparts])[]
..filter: search([plantparts])[]
..summary: search([plantparts])[]
..running: search; search([monoterpene])[]
..filter: search([monoterpene])[]
..summary: search([monoterpene])[]
..running: species; species([binomial])[]
SP: /home/ambarish123/RiceOROryzanew..filter: species([binomial])[]
..summary: species([binomial])[]
..create data tables
Exception in thread "main" java.lang.RuntimeException: Null metadataByTreename
	at org.contentmine.cproject.util.DataTablesTool.setMetadataByTreename(DataTablesTool.java:463)
	at org.contentmine.ami.plugins.CommandProcessor.createDataTables(CommandProcessor.java:210)
	at org.contentmine.ami.AMIProcessor.runSearches(AMIProcessor.java:116)
	at org.contentmine.ami.AMIProcessor.runSearchesAndCooccurrence(AMIProcessor.java:191)
	at org.contentmine.ami.tools.AMISearch.runAMISearches(AMISearch.java:47)
	at org.contentmine.ami.tools.AMISearch.main(AMISearch.java:28)

```

### * As an output, it could not generate `entries.DataTables.html`  and  `cooccurrence` results.

**Comment by ambarishK** [comment]
### Test run status of ami-search-new tool/plugin of ami20190218a.jar

#### * Run time log

```
ambarish123@ubuntu:~$ ami-search-new -p RiceOROryzanew1/ --dictionary country gene plantparts drugs

Generic values (AMISearchTool)
================================
basename            null
cproject            /home/ambarish123/RiceOROryzanew1
ctree               
cTreeList           [RiceOROryzanew1/PMC5991738, RiceOROryzanew1/PMC6086036, RiceOROryzanew1/PMC6173730, RiceOROryzanew1/PMC6203701, RiceOROryzanew1/PMC6205584, RiceOROryzanew1/PMC6208651, RiceOROryzanew1/PMC6213974, RiceOROryzanew1/PMC6222575, RiceOROryzanew1/PMC6249995, RiceOROryzanew1/PMC6265930, RiceOROryzanew1/PMC6267922, RiceOROryzanew1/PMC6278296, RiceOROryzanew1/PMC6283022, RiceOROryzanew1/PMC6311050, RiceOROryzanew1/PMC6321642, RiceOROryzanew1/PMC6337394, RiceOROryzanew1/PMC6339128, RiceOROryzanew1/PMC6339371, RiceOROryzanew1/PMC6345233, RiceOROryzanew1/PMC6357162]
dryrun              false
excludeBase         null
excludeTrees        null
file types          []
forceMake           false
includeBase         null
includeTrees        null
log4j               
logfile             null
verbose             0

Specific values (AMISearchTool)
================================
dictionaryList       [country, gene, plantparts, drugs]
dictionaryTop        null
dictionarySuffix     [xml]
ignorePlugins        []

cProject: RiceOROryzanew1
0    [main] DEBUG org.contentmine.ami.tools.AMISearchTool  - cannot find builtin dictionary: country
cannot find dictionary: country
23   [main] DEBUG org.contentmine.ami.tools.AMISearchTool  - cannot find builtin dictionary: plantparts
cannot find dictionary: plantparts
26   [main] DEBUG org.contentmine.ami.tools.AMISearchTool  - cannot find builtin dictionary: drugs
cannot find dictionary: drugs
35   [main] DEBUG org.contentmine.ami.tools.AMISearchTool  - SEARCH running legacy processors
940  [main] DEBUG org.contentmine.ami.plugins.CommandProcessor  - running NORMA -i fulltext.xml -o scholarly.html --transform nlm2html --project RiceOROryzanew1
PMC5991738 .PMC6086036 PMC6173730 PMC6203701 PMC6205584 PMC6208651 PMC6213974 PMC6222575 PMC6249995 PMC6265930 PMC6267922 .PMC6278296 PMC6283022 PMC6311050 PMC6321642 PMC6337394 PMC6339128 PMC6339371 PMC6345233 PMC6357162 SEARCH running JSON bibliography
running: word; word([frequencies])[{xpath:@count>20}, {w.stopwords:pmcstop.txt stopwords.txt}]
..filter: word([frequencies])[{xpath:@count>20}, {w.stopwords:pmcstop.txt stopwords.txt}]
..summary: word([frequencies])[{xpath:@count>20}, {w.stopwords:pmcstop.txt stopwords.txt}]
..running: search; search([country])[]
..filter: search([country])[]
..summary: search([country])[]
..running: gene; gene([human])[]
180053 [main] DEBUG org.contentmine.ami.dictionary.gene.HGNCDictionary  - is /org/contentmine/ami/plugins/gene/hgnc/hgnc.xml
..filter: gene([human])[]
..summary: gene([human])[]
..running: search; search([plantparts])[]
..filter: search([plantparts])[]
..summary: search([plantparts])[]
..running: search; search([drugs])[]
..filter: search([drugs])[]
..summary: search([drugs])[]
..create data tables
```
#### * Run is successful and it is generating `entries.DataTables.html` file containing bibliographic information into 2nd column. But the message related - " cannot find builtin dictionary: country cannot find dictionary: <search term> " persists.

#### * Screenshot of the browser window displaying the result.
![entries datattables1](https://user-images.githubusercontent.com/36997739/52958848-c73fff00-3349-11e9-973a-a9af3bf0143f.png)
